version: "2.3"

services:
  autogoal-core:
    container_name: autogoal-core
    hostname: autogoal-core
    image: autogoal/autogoal:core
    ports:
      - 8500:8501
      - 8000:8000
    volumes: 
      - "./autogoal:/usr/lib/python3/dist-packages/autogoal"
      - "./vendor/illiterate/illiterate:/usr/lib/python3/dist-packages/illiterate"
      - ".:/home/coder/autogoal"
      - "~/.ssh:/home/coder/.ssh"
      - "~/.gitconfig:/home/coder/.gitconfig"
    user: "1000:1000"

  autogoal-sklearn:
    container_name: autogoal-sklearn
    hostname: autogoal-sklearn
    image: autogoal/autogoal:sklearn
    ports:
      - 8502:8501
      - 8002:8000
    volumes: 
      - "./autogoal:/usr/lib/python3/dist-packages/autogoal"
      - "./autogoal-remote:/usr/lib/python3/dist-packages/autogoal-remote"
      - "./vendor/illiterate/illiterate:/usr/lib/python3/dist-packages/illiterate"
      - ".:/home/coder/autogoal"
      - "~/.ssh:/home/coder/.ssh"
      - "~/.gitconfig:/home/coder/.gitconfig"
    user: "1000:1000"
  
  autogoal-nltk:
    container_name: autogoal-nltk
    hostname: autogoal-nltk
    image: autogoal/autogoal:nltk
    ports:
      - 8503:8501
      - 8003:8000
    volumes: 
      - "./autogoal:/usr/lib/python3/dist-packages/autogoal"
      - "./autogoal-remote:/usr/lib/python3/dist-packages/autogoal-remote"
      - "./vendor/illiterate/illiterate:/usr/lib/python3/dist-packages/illiterate"
      - ".:/home/coder/autogoal"
      - "~/.ssh:/home/coder/.ssh"
      - "~/.gitconfig:/home/coder/.gitconfig"
    user: "1000:1000"