!yamlable/autogoal.remote.connectionConfig.ConnectionConfig
connections:
- !yamlable/autogoal.remote.connectionAlias.Alias
  ip: 172.20.0.2
  name: new
  port: 8000
- !yamlable/autogoal.remote.connectionAlias.Alias
  ip: 172.20.0.2
  name: new
  port: 8000
- !yamlable/autogoal.remote.connectionAlias.Alias
  ip: 172.20.0.2
  name: new
  port: 8000
- !yamlable/autogoal.remote.connectionAlias.Alias
  ip: 172.20.0.2
  name: new
  port: 8000
- !yamlable/autogoal.remote.connectionAlias.Alias
  ip: 172.18.0.2
  name: new
  port: 8000
- !yamlable/autogoal.remote.connectionAlias.Alias
  ip: 172.18.0.2
  name: new
  port: 8000
- !yamlable/autogoal.remote.connectionAlias.Alias
  ip: 172.18.0.2
  name: new
  port: 8000
- !yamlable/autogoal.remote.connectionAlias.Alias
  ip: 172.18.0.2
  name: new
  port: 8000
- !yamlable/autogoal.remote.connectionAlias.Alias
  ip: 172.18.0.2
  name: new
  port: 8000
- !yamlable/autogoal.remote.connectionAlias.Alias
  ip: 172.18.0.3
  name: nltk
  port: 8000
- !yamlable/autogoal.remote.connectionAlias.Alias
  ip: 172.18.0.3
  name: nltk
  port: 8000
