!yamlable/autogoal.remote.connectionConfig.ConnectionConfig
connections:
  remote-nltk: !yamlable/autogoal.remote.connectionAlias.Alias
    ip: 172.18.0.3
    name: remote-nltk
    port: 8000
  remote-sklearn: !yamlable/autogoal.remote.connectionAlias.Alias
    ip: 172.18.0.3
    name: remote-sklearn
    port: 8000
